### ISSUE TITLE
Problem with text after installing the lastest update

### ISSUE THREAD

**Issue by DiabloRecon** [bayaraa/d2gl#95] opened 2023-07-22 06:40 UTC
Text appears to be missing at some parts and is unreadable. 
![Screenshot 2023-07-22 013903](https://github.com/bayaraa/d2gl/assets/139571777/0b99410e-fefd-493e-8d93-f96308f38e9c)
![Screenshot 2023-07-22 013940](https://github.com/bayaraa/d2gl/assets/139571777/a1ee9ddb-74bd-4c6e-89aa-a9be260934e4)
![Screenshot 2023-07-22 015731](https://github.com/bayaraa/d2gl/assets/139571777/fbbb1028-df2a-4950-876d-bdda8e0da426)

You can also see the character's model in the minimap which has the same problem as the text
![Screenshot 2023-07-22 014730](https://github.com/bayaraa/d2gl/assets/139571777/3572cafd-8f36-4e02-91ff-19fa22d278d7)

**Comment by DiabloRecon** [comment] 2023-07-22 07:09
Doesn't help.

**Comment by bayaraa** [comment] 2023-07-22 07:12
what d2 version with what mods? any log?

**Comment by DiabloRecon** [comment] 2023-07-22 07:16
Diablo 2 LOD 1.13c with PlugY 11.02 and BH maphack 1.9.9.

[d2log.txt](https://github.com/bayaraa/d2gl/files/12135910/d2log.txt)

**Comment by rnd2k** [comment] 2023-07-22 19:07
I had a similar problem, try to remove d2gl.ini and reconfigure via Ctrl+O

**Comment by DiabloRecon** [comment] 2023-07-22 19:20
That fixed the problem but If I try to change Bloom and or Color Grading the same problem appears.

**Comment by bayaraa** [comment] 2023-07-23 01:10
is it caused by bloom or lut?
previous version hadn't this issue?

**Comment by DiabloRecon** [comment] 2023-07-23 01:23
Previous version didn't have this issue. It is caused by Bloom and Color Grading.

**Comment by bayaraa** [comment] 2023-07-23 03:07
@DiabloRecon is this fix the issue?
[glide3x.zip](https://github.com/bayaraa/d2gl/files/12137913/glide3x.zip)

**Comment by DiabloRecon** [comment] 2023-07-23 03:20
Yes, it does fix the issue. Thank you :)

**Comment by bayaraa** [comment] 2023-07-23 06:07
fix merged in 1.3.1.

**Closed by bayaraa** 2023-07-23 06:07 UTC
